// MinimalToken Package Configuration
// This file is auto-generated by upload_dar.py
// You can manually add old versions for backward compatibility

export const MINIMAL_TOKEN_PACKAGE_CONFIG = {
  // Current active version
  currentVersion: '1.0.0',
  currentPackageId: '1bf66b0c9774ca1de9a075c810b443c2fe3638c59c07da7c8034b04650e3352e',

  // All deployed versions (newest first)
  // When upload_dar.py runs, it adds the new version and keeps existing ones
  versions: {
    '1.0.0': '1bf66b0c9774ca1de9a075c810b443c2fe3638c59c07da7c8034b04650e3352e'
    // Uncomment older versions if you need backward compatibility:
    // '2.4.0': 'bc5800fb102ebab939780f60725fc87c5c0f93c947969c8b2fc2bb4f87d471de',
    // '2.2.0': 'c90d4ebea4593e9f5bcb46291cd4ad5fef08d94cb407a02085b30d92539383ae',
    // '2.1.0': 'c598823710328ed7b6b46a519df06f200a6c49de424b0005c4a6091f8667586d',
    // '2.0.1': '2399d6f39edcb9611b116cfc6e5b722b65b487cbb71e13a300753e39268f3118',
    // '2.0.0': 'eccbf7c592fcae3e2820c25b57b4c76a434f0add06378f97a01810ec4ccda4de'
  }
};

export default MINIMAL_TOKEN_PACKAGE_CONFIG;
