#!/bin/bash
set -e

# Upload MinimalToken DAR to Canton LocalNet participants
# Auto-detects version from daml.yaml and updates package configuration
#
# Usage:
#   ./scripts/upload_dar.sh [version]
#
# If version is not provided, it will be read from daml.yaml

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DAML_PROJECT="$PROJECT_ROOT/daml/minimal-token"
DAML_YAML="$DAML_PROJECT/daml.yaml"
CONFIG_FILE="$PROJECT_ROOT/src/config/packageConfig.js"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}$1${NC}"
}

log_success() {
    echo -e "${GREEN}$1${NC}"
}

log_warning() {
    echo -e "${YELLOW}$1${NC}"
}

log_error() {
    echo -e "${RED}$1${NC}"
}

# Read version from daml.yaml
read_version_from_yaml() {
    if [ ! -f "$DAML_YAML" ]; then
        log_error "❌ daml.yaml not found at: $DAML_YAML"
        exit 1
    fi

    # Extract version using grep and awk
    VERSION=$(grep "^version:" "$DAML_YAML" | awk '{print $2}' | tr -d '"' | tr -d "'")
    
    if [ -z "$VERSION" ]; then
        log_error "❌ Could not find 'version' field in daml.yaml"
        exit 1
    fi

    echo "$VERSION"
}

# Get DAR file path
get_dar_path() {
    local version=$1
    echo "$DAML_PROJECT/.daml/dist/minimal-token-${version}.dar"
}

# Upload DAR to a participant
upload_dar_to_participant() {
    local participant_name=$1
    local port=$2
    local dar_b64=$3
    local version=$4

    log_info "🚀 Uploading to $participant_name (localhost:$port)..."

    local upload_request=$(cat <<EOF
{
  "dars": [{
    "bytes": "$dar_b64",
    "description": "MinimalToken v${version} - ProposeBurn/AcceptBurn pattern"
  }],
  "vet_all_packages": true,
  "synchronize_vetting": true
}
EOF
)

    local result=$(grpcurl -plaintext -d "$upload_request" \
        "localhost:$port" \
        com.digitalasset.canton.admin.participant.v30.PackageService/UploadDar 2>&1)

    if [ $? -ne 0 ]; then
        log_error "❌ $participant_name upload failed"
        echo "$result"
        exit 1
    fi

    log_success "✅ $participant_name upload successful"
    echo "$result"
}

# Vet DAR on a participant
vet_dar_on_participant() {
    local participant_name=$1
    local port=$2
    local package_id=$3

    log_info "  🔒 Vetting on $participant_name..."

    local vet_request=$(cat <<EOF
{
  "main_package_id": "$package_id",
  "synchronize": true
}
EOF
)

    local result=$(grpcurl -plaintext -d "$vet_request" \
        "localhost:$port" \
        com.digitalasset.canton.admin.participant.v30.PackageService/VetDar 2>&1)

    if [ $? -ne 0 ]; then
        log_warning "  ⚠️  $participant_name vetting warning: $result"
    else
        log_success "  ✅ $participant_name vetting successful"
    fi
}

# Extract package ID from upload response
extract_package_id() {
    local response=$1
    # Extract first darId from JSON response
    echo "$response" | grep -o '"darIds":\s*\["[^"]*"' | \
        grep -o '[a-f0-9]\{64\}' | head -1
}

# Update package configuration
update_package_config() {
    local package_id=$1
    local version=$2

    log_info ""
    log_info "📝 Updating package configuration: $CONFIG_FILE"

    # Read existing config if it exists
    local versions_block=""
    if [ -f "$CONFIG_FILE" ]; then
        # Extract existing versions
        versions_block=$(grep -oP "versions:\s*\{[^}]*\}" "$CONFIG_FILE" | \
            grep -oP "'[^']+'\s*:\s*'[^']+'" || echo "")
    fi

    # Add new version to the block
    if [ -n "$versions_block" ]; then
        versions_block="${versions_block}\n    '${version}': '${package_id}'"
    else
        versions_block="'${version}': '${package_id}'"
    fi

    # Remove duplicates and sort (newest first)
    versions_block=$(echo -e "$versions_block" | \
        awk '!seen[$0]++' | \
        sort -r -t: -k1)

    # Format for JS object
    versions_formatted=$(echo -e "$versions_block" | \
        awk '{printf "    %s", $0; if(NR<line_count) printf ",\n"}' \
        line_count=$(echo -e "$versions_block" | wc -l))

    # Create new config file
    cat > "$CONFIG_FILE" <<EOF
// MinimalToken Package Configuration
// This file is auto-generated by upload_dar.sh

export const MINIMAL_TOKEN_PACKAGE_CONFIG = {
  // Current active version
  currentVersion: '${version}',
  currentPackageId: '${package_id}',

  // All deployed versions (newest first)
  versions: {
${versions_formatted}
  }
};

export default MINIMAL_TOKEN_PACKAGE_CONFIG;
EOF

    log_success "✅ Updated package configuration"
    log_info "   Current version: $version"
    log_info "   Package ID: $package_id"
}

# Main execution
main() {
    log_info "🚀 Canton DAR Upload Tool"
    echo ""

    # Get version from command line or daml.yaml
    if [ $# -gt 1 ]; then
        echo "Usage: $0 [version]"
        echo ""
        echo "If version is not provided, it will be read from daml.yaml"
        echo ""
        echo "Examples:"
        echo "  $0              # Auto-detect from daml.yaml"
        echo "  $0 1.0.0        # Use specific version"
        exit 1
    fi

    if [ $# -eq 1 ]; then
        VERSION=$1
        log_info "📝 Using version from command line"
    else
        log_info "📝 Reading version from daml.yaml..."
        VERSION=$(read_version_from_yaml)
        log_success "✅ Found version: $VERSION"
    fi

    DAR_PATH=$(get_dar_path "$VERSION")

    echo ""
    log_info "📦 Version: $VERSION"
    log_info "📁 DAR path: $DAR_PATH"
    echo ""

    # Check if DAR file exists
    if [ ! -f "$DAR_PATH" ]; then
        log_error "❌ DAR file not found: $DAR_PATH"
        log_warning "💡 Did you run 'daml build' first?"
        echo ""
        echo "To build:"
        echo "  cd daml/minimal-token"
        echo "  daml build"
        exit 1
    fi

    # Read and encode DAR file
    log_info "📦 Reading DAR file: $DAR_PATH"
    DAR_B64=$(base64 -i "$DAR_PATH")
    DAR_SIZE=$(wc -c < "$DAR_PATH" | tr -d ' ')
    log_success "✅ Encoded DAR file ($DAR_SIZE bytes)"
    echo ""

    # Upload to app-provider (port 3902)
    UPLOAD_RESPONSE=$(upload_dar_to_participant "app-provider" "3902" \
        "$DAR_B64" "$VERSION")
    
    # Extract package ID from response
    PACKAGE_ID=$(extract_package_id "$UPLOAD_RESPONSE")
    
    if [ -z "$PACKAGE_ID" ]; then
        log_error "❌ Could not extract package ID from response"
        exit 1
    fi
    
    log_success "📦 Package ID: $PACKAGE_ID"
    echo ""

    # Upload to app-user (port 2902)
    upload_dar_to_participant "app-user" "2902" "$DAR_B64" "$VERSION" \
        > /dev/null
    echo ""

    # Vet on both participants
    log_info "🔒 Vetting DAR on participants..."
    vet_dar_on_participant "app-provider" "3902" "$PACKAGE_ID"
    vet_dar_on_participant "app-user" "2902" "$PACKAGE_ID"
    log_success "✅ DAR vetting complete"

    # Update package configuration
    update_package_config "$PACKAGE_ID" "$VERSION"

    echo ""
    log_success "✅ Upload complete!"
    echo ""
    log_info "📝 Configuration updated automatically in:"
    log_info "   - src/config/packageConfig.js"
    echo ""
    log_info "💡 Make sure your services import from packageConfig.js"
    log_info "   to use the new version"
}

# Run main function
main "$@"

